arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
supported-locales:
  - en
  - hi
  - mr
  - te
  - ta
  - bn
untranslated-messages-file: untranslated_messages.json
